FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm i -g pnpm
COPY . /app
WORKDIR /app


FROM base AS build
ARG PUBLIC_API_URL
ARG PRIVATE_API_URL
RUN --mount=type=cache,id=s/388552ad-7ddf-4c51-b2b3-dddb24e7adac-/pnpm/store,target=/pnpm/store pnpm install --frozen-lockfile --filter app...
RUN pnpm turbo build --filter app

FROM caddy:alpine
COPY --from=base /app/apps/app/caddy/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/apps/app/.output/public /var/www
